### ISSUE TITLE
The equations in the paper are incomprehensible

### ISSUE THREAD

**Issue by pc-cp** [cly234/DeepClustering-ConNR#1]
Hi, very inspiring work. 
But I have some confusion about equation 12 and 13 in the paper. In which why equation 12 is linearly increasing? There is only one variable $t$ in its formula that lies on the denominator and I always thought that $fr^{(t)}$ should be decreasing? And also is $B^{(t)}$ in equation 13 contains features that are not on the boundary? Very much looking forward to your reply.

**Comment by cly234** [comment]
Thanks for your interest in our work! Regarding the first question, we notice that this is a typo, where t and T should be swapped to make sure $fr^{(t)}$ is increasing as originally intended. For the second, $B^{(t)}$ dynamically changes from filtering out boundary samples to increasingly involving boundary samples, which is a progressive strategy to make the model more robust to the noise incurred by neighborhood retrieval.

**Comment by pc-cp** [comment]
Thank you for your reply. I have some questions about equations 13 and 14 of the article. Does $B^{(t)}$ in Eq. 13 correspond to a set consisting of bounded samples? My reasoning for this guess is that in equation 14 you exclude $B^{(t)}$. If so, why is $r_i <= \sigma^{(t)} $? Equation 11 states that a larger $r_i$ means it sits on the boundary. I think equation 13 should be $r_i >= \sigma^{(t)} $? Looking forward to your reply.

**Comment by cly234** [comment]
Hi, thanks for pointing out this, by definition we mean $B^{(t)}$ as the boundary samples which need to be filtered out at epoch t, so there should be $>$ instead of $\leq$ in Eq. 13. We have fixed this error in arxiv version, or you can check the code implementation for more details.
