### ISSUE TITLE
Get some problems when reproducing your code

### ISSUE THREAD

**Issue by Regan-Zhang** [cly234/DeepClustering-ConNR#3]
Thank you for your great work! And I am so interested in your work. But when I try to reproduce you project, the errors come. For example, the error "Unsupported gpu architecture compute_86" ouputs when I execute "sh make.sh" to compile your extensions.  Luckily, I degrate my cuda and pytorch to fix this. But another error comes when I "sh run.sh", the error is "Import Error: libcudart.so.10.1". The setting of my computer is Ubuntu 20.04, Nvidia GeForce 3090 gpu, pytorch1.16.0, cuda11.0. Could you show me your environment setting? Thank you so much.

**Comment by cly234** [comment]
Thanks for your interest in our work! The environment setting is equipped with Ubuntu20.04, python3.8.10, pytorch 1.11.0+cu113, cuda11.3 on RTX 4090s
